name: askforfeedback
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  search_widget: ^1.0.2
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.0
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Black.ttf
         - asset: fonts/Poppins-BlackItalic.ttf
         - asset: fonts/Poppins-Bold.ttf
         - asset: fonts/Poppins-Regular.ttf
         - asset: fonts/Poppins-BoldItalic.ttf
         - asset: fonts/Poppins-ExtraBold.ttf
         - asset: fonts/Poppins-ExtraLight.ttf
         - asset: fonts/Poppins-ExtraLightItalic.ttf
         - asset: fonts/Poppins-Light.ttf
         - asset: fonts/Poppins-LightItalic.ttf
         - asset: fonts/Poppins-Medium.ttf
         - asset: fonts/Poppins-MediumItalic.ttf
         - asset: fonts/Poppins-SemiBold.ttf
         - asset: fonts/Poppins-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
